# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1e8079544cc7786beec9a907103e3b0ce5dd120fa0d340d6db0f6eba2fc3a6514b0e2f9111167edc791c24103a83097f568fd2281baab7a9bc97d9968e5fc0c9

test:
  secret_key_base: 8c206183836bd1535db68ffbb5893263bc3313fe2de1cb2a112628f4fb387b03d57147c2e510373df2e49668511d6688800a26089d1f8011d5a8a681680eb48f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
